exit 1

diff --git a/.github/workflows/codecov.yml b/.github/workflows/codecov.yml
--- a/.github/workflows/codecov.yml
+++ b/.github/workflows/codecov.yml
@@ -37,6 +37,8 @@ jobs:
       - run: npm run test:junit
       - run: |
           curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov
+          exec 5>&1
           for dir in packages/*; do
-            ./codecov --rootDir "${dir}" --flags "$(basename "${dir}")" --verbose || exit 1
+            OUTPUT=$(./codecov --flags "${PWD}/$(basename "${dir}")" --verbose | tee /dev/fd/5)
+            echo "${OUTPUT}" | grep --quiet 'error' && exit 1
           done
